spring.application.name=supportflow
spring.datasource.url=jdbc:postgresql://localhost:5432/supportflow
spring.datasource.username=supportflow_user
spring.datasource.password=supportflow_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true